### PR TITLE
Switch React docs to hooks-first

### PR DESCRIPTION
**Pull request by karlhorky**
Hi there, thanks for Vanta! Looks really cool :)

Since the new version of the React docs is also now hooks-first (see https://beta.reactjs.org/), I wanted to open a PR to switch the React docs here to also be hooks first, and also included a new example on JSFiddle.

### CODE REVIEW

**Comment by karlhorky** [comment]
I noticed that both React examples on JSFiddle (also the original one linked in the docs) don't really work as I would expect though, so maybe there's some bug preventing Vanta from showing up?

Screen Shot 2022-01-04 at 10 06 44

**Comment by Ading163** [comment]
Hello! Man, I have the same problem as you

**Comment by tengbao** [comment]
thanks for the bug report. i updated the fiddle: https://jsfiddle.net/1mcr7x50/2/ 
and the readme: https://github.com/tengbao/vanta

**Comment by karlhorky** [comment]
Great, thanks @tengbao !

**Pull request closed without merging**
